### ISSUE TITLE
Add `GetAuthTicketForWebApi` call

### ISSUE THREAD

**Issue by fire** [hajimehoshi/go-steamworks#12]
```
HAuthTicket GetAuthTicketForWebApi( const char *pchIdentity );
```
Hi, I wanted to add the GetAuthTicketForWebApi call.

Let me know if there's anything I need to know.

**Comment by hajimehoshi** [comment]
Contributions are always welcome.

**Comment by fire** [comment]
I was not able to complete this, but my last draft was at https://github.com/fire/go-steamworks/tree/web-auth-ticket
